<?php
namespace app\admin\controller;

use think\facade\Session;
use think\Request;
use think\Controller as Controller;
class Base extends Controller
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->assign("public","../../../../static");//静态文件夹路径
        $this->assign("adname",Session::get('adname'));
    }

}